name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Run client
        working-directory: ./client
        run: yarn --ignore-scripts
        run: yarn test
      - name: Run consumer
        working-directory: ./consumer
        run: yarn --ignore-scripts
        run: yarn test
      - name: Run subscriber
        working-directory: ./subscriber
        run: yarn --ignore-scripts
        run: yarn test
